# verifcar as PK
# verficar as FK (on_delete)
from django.db import models


class Clientes(models.Model):
    clie_codigo = models.DecimalField(unique=True, max_digits=8, decimal_places=0)
    clie_nome = models.CharField(max_length=80, blank=True, null=True)
    clie_razaosocial = models.CharField(max_length=80, blank=True, null=True)
    clie_nomecartao = models.CharField(max_length=30, blank=True, null=True)
    clie_tipo = models.CharField(max_length=1)
    clie_cnpjcpf = models.CharField(max_length=14, blank=True, null=True)
    clie_rgie = models.CharField(max_length=20, blank=True, null=True)
    clie_ufexprg = models.CharField(max_length=2, blank=True, null=True)
    clie_endres = models.CharField(max_length=50, blank=True, null=True)
    clie_endresnumero = models.CharField(max_length=20, blank=True, null=True)
    clie_endrescompl = models.CharField(max_length=50, blank=True, null=True)
    clie_bairrores = models.CharField(max_length=30, blank=True, null=True)
    clie_muni_codigo_res = models.DecimalField(max_digits=6, decimal_places=0, blank=True, null=True)
    clie_cepres = models.CharField(max_length=8, blank=True, null=True)
    clie_foneres = models.CharField(max_length=15, blank=True, null=True)
    clie_fonecel = models.CharField(max_length=15, blank=True, null=True)
    clie_email = models.CharField(max_length=200, blank=True, null=True)
    clie_obs = models.CharField(max_length=200, blank=True, null=True)
    clie_dtcad = models.DateField(blank=True, null=True)
    clie_dataalt = models.DateField(blank=True, null=True)
    clie_usualt = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
    clie_unid_codigo = models.CharField(max_length=3, blank=True, null=True)
    clie_usua_codigo = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
    clie_filiacao = models.CharField(max_length=100, blank=True, null=True)
    clie_contribuinte = models.CharField(max_length=1, blank=True, null=True)
    clie_vend_codigo = models.CharField(max_length=4, blank=True, null=True)
    clie_vend_alternativos = models.CharField(max_length=50, blank=True, null=True)
    clie_rota_codigo = models.CharField(max_length=3, blank=True, null=True)
    clie_caractrib = models.CharField(max_length=3, blank=True, null=True)
    clie_tipos = models.CharField(max_length=100, blank=True, null=True)
    clie_fpgt_codigo = models.CharField(max_length=200, blank=True, null=True)
    clie_lpgt_codigo = models.CharField(max_length=3, blank=True, null=True)
    clie_status = models.CharField(max_length=1, blank=True, null=True)
    clie_ramoatividade = models.CharField(max_length=50, blank=True, null=True)
    clie_emailnfe = models.CharField(max_length=200, blank=True, null=True)
    clie_rotaunidades = models.CharField(max_length=1000, blank=True, null=True)
    clie_codcliint = models.CharField(max_length=50, blank=True, null=True)
    clie_codvinc = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
    clie_extra1 = models.CharField(max_length=10, blank=True, null=True)
    clie_extra2 = models.CharField(max_length=50, blank=True, null=True)
    clie_extra3 = models.CharField(max_length=100, blank=True, null=True)
    clie_extra4 = models.CharField(max_length=100, blank=True, null=True)
    clie_extra5 = models.CharField(max_length=200, blank=True, null=True)
    clie_extra6 = models.CharField(max_length=200, blank=True, null=True)
    clie_extra7 = models.DecimalField(max_digits=15, decimal_places=5, blank=True, null=True)
    clie_extra8 = models.DecimalField(max_digits=15, decimal_places=5, blank=True, null=True)
    clie_extra9 = models.DateField(blank=True, null=True)
    clie_cpfnota = models.CharField(max_length=1, blank=True, null=True)
    clie_extra10 = models.CharField(max_length=10, blank=True, null=True)
    clie_extra11 = models.CharField(max_length=10, blank=True, null=True)
    clie_extra12 = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'clientes'
